media:
  - name: images
    label: Images
    input: assets/images
    output: /images
    extensions:
      - png
      - jpg
      - jpeg
      - gif

content:
  - name: home
    label: Home
    type: file
    path: assets/index.md
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: about
    label: About Us
    type: file
    path: About Us.html
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: contact
    label: Contact
    type: file
    path: Contact.html
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: team
    label: Our Team
    type: file
    path: Our Team.html
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: projects
    label: Projects
    type: file
    path: Projects.html
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: services
    label: Services
    type: file
    path: Services.html
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: testimonial
    label: Testimonials
    type: file
    path: Testimonial.html
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true

components:
  hero:
    label: Hero Section
    type: object
    fields:
      - name: headline
        label: Headline
        type: text
        required: true
      - name: subheadline
        label: Subheadline
        type: text
        required: true
      - name: image
        label: Background Image
        type: image
        required: true


